# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ctxapacusers',
            fields=[
                ('user_name', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=50)),
                ('emp_contact', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skills', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField()),
                ('skill_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apacskills.Skills')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apacskills.Ctxapacusers')),
            ],
        ),
    ]
