# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apacskills', '0002_auto_20171205_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctxapacusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skills_map',
            name='skill_level',
            field=models.CharField(choices=[('S', 'SME'), ('Y', 'Support')], max_length=1),
        ),
    ]
