# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ctxapacusers_skills_skills_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctxapacusers',
            name='id',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='id',
        ),
        migrations.AlterField(
            model_name='ctxapacusers',
            name='user_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
